name: documentation

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ansible_collections/community/elastic
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path:  ansible_collections/community/elastic

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install ansible-base (devel)
        run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: Build collection
        run: ansible-galaxy collection build .

      - name: Install collection
        run: ansible-galaxy collection install community-elastic-*.tar.gz

      - name: Install ansible-doc-extractor
        run: pip install wheel setuptools ansible-doc-extractor --upgrade

      - name: Install rstdoc
        run: pip install -v rstdoc

      - name: Create docs dir
        run: mkdir docs

      - name: Create rst files from modules
        run: ansible-doc-extractor ./docs plugins/modules/elastic_*.py

      - name: Create collection index document
        run: |
          echo "# Elastic Ansible Collection Documentation" > docs/index.md
          echo "## Modules" >> docs/index.md
          find plugins/modules -type f -name 'elastic_*.py' -exec bash -c 'echo "- [$(basename "{}" ".py")]($(basename {} .py).html)"' \; >> docs/index.md

      - name: Create module html documents from rst files
        run: |
          find ./docs -type f -name 'elastic_*.rst' -maxdepth 1 -exec bash -c 'rstdoc {} "docs/$(basename "{}" ".rst").html" rst_html' \;

      - name: Remove intermediary rst docs
        run: find docs/ -name '*.rst' -delete

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: ansible_collections/community/elastic/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
